### ISSUE TITLE
Remove Chromecast Icon from Animations

### ISSUE THREAD

**Issue by Kelwan** [ecsact-dev/website#74]
Read here for more information: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

**Comment by zaucy** [comment]
fixed in c3100c4c4d3214555ee58a16c7b09bb9bfcc5093

I added 
```
disablepictureinpicture
disableremoteplayback
x-webkit-airplay="deny"
```

to all the video tags. Shouldn't be a problem anymore.
